# Generated by Django 5.1.4 on 2025-01-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
