# Generated by Django 5.1.4 on 2025-01-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto_delete',
            field=models.BooleanField(default=False),
        ),
    ]
